import { type MHWIMonsterSpecies } from "@prisma/client";

const frenchMonsterlist = {
  Anjanath: "Anjanath",
  Barroth: "Barroth",
  Bazelgeuse: "Bazelgeuse",
  Behemoth: "Béhémoth",
  Deviljho: "Deviljho",
  Diablos: "Diablos",
  BlackDiablos: "Diablos Noire",
  Dodogama: "Dodogama",
  GreatGirros: "Grand Girros",
  GreatJagras: "Grand Jagras",
  Jyuratidus: "Jyuratodus",
  Kirin: "Kirin",
  KuluYaKu: "Kulu-Ya-Ku",
  KulveTaroth: "Kulve Taroth",
  KushalaDaora: "Kushala Daora",
  Lavasioth: "Lavasioth",
  Legiana: "Legiana",
  OldLeshen: "Vieux Leshen",
  Lunastra: "Lunastra",
  Nergigante: "Nergigante",
  Odogaron: "Odogaron",
  Paolumu: "Paolumu",
  PukeiPukei: "Pukei-Pukei",
  Radobaan: "Radobaan",
  Rathalos: "Rathalos",
  AzurRathalos: "Rathalos Azure",
  Rathian: "Rathian",
  PinkRathian: "Rathian Sakura",
  Teostra: "Teostra",
  TobiKadashi: "Tobi-Kadashi",
  TzitziYaKu: "Tzitzi-Ya-Ku",
  Uragaan: "Uragaan",
  VaalHazak: "Vaal Hazak",
  Leshen: "Leshen",
  XenoJiva: "Xeno'Jiva",
  ZorahMagdaros: "Zorah Magdaros",
  Banbaro: "Banbaro",
  Beotodus: "Beotodus",
  TobiKadashiViper: "Tobi-Kadashi Vipère",
  PaolumuBelladone: "Paolumu Belladone",
  Barioth: "Barioth",
  Nargacuga: "Nargacuga",
  Glavenus: "Glavenus",
  Tigrex: "Tigrex",
  Brachydios: "Brachydios",
  ShriekingLegiana: "Legiana Blizzard",
  FulgurAnjanath: "Anjanath Tonnerre",
  AcidicGlavenus: "Glavenus Acide",
  EbonyOdogaron: "Odogaron Désastre",
  Velkhana: "Velkhana",
  SeethingBazelgeuse: "Bazelgeuse Vulcan",
  BlackveilVaalHazak: "Vaal Hazak Fléau",
  Namielle: "Namielle",
  SavageDeviljho: "Deviljho Carnage",
  RuinerNergigante: "Nergigante Chaos",
  SharaIshvalda: "Shara Ishvalda",
  Zinogre: "Zinogre",
  YianGaruga: "Yian Garuga",
  ScarredYianGaruga: "Yian Garuga Balafré",
  GoldRathian: "Rathian d'Or",
  SilverRathalos: "Rathalos d'Argent",
  BruteTigrex: "Tigrex Berserker",
  CoralPukeiPukei: "Pukei-Pukei Corail",
  StygianZinogre: "Zinogre Stygien",
  Rajang: "Rajang",
  FuriousRajang: "Rajang Orage",
  FrostfangBarioth: "Barioth crocgivre",
  RagingBrachydios: "Brachydios Tempête",
  SafiJiva: "Safi'Jiva",
  Alatreon: "Alatréon",
  Fatalis: "Fatalis",
  GreenNargacuga: "Nargacuga Vert",
  HellbladeGlavenus: "Glavenus Lame-chaos",
  CrimsonFatalis: "Fatalis Pourpre",
  WhiteFatalis: "Fatalis Blanc",
  Abiogladius: "Abiogladius",
}
const englishMonsterlist = {
  Anjanath: "Anjanath",
  Barroth: "Barroth",
  Bazelgeuse: "Bazelgeuse",
  Behemoth: "Behemoth",
  Deviljho: "Deviljho",
  Diablos: "Diablos",
  BlackDiablos: "Black Diablos",
  Dodogama: "Dodogama",
  GreatGirros: "Great Girros",
  GreatJagras: "Great Jagras",
  Jyuratidus: "Jyuratodus",
  Kirin: "Kirin",
  KuluYaKu: "Kulu-Ya-Ku",
  KulveTaroth: "Kulve Taroth",
  KushalaDaora: "Kushala Daora",
  Lavasioth: "Lavasioth",
  Legiana: "Legiana",
  OldLeshen: "Old Leshen",
  Lunastra: "Lunastra",
  Nergigante: "Nergigante",
  Odogaron: "Odogaron",
  Paolumu: "Paolumu",
  PukeiPukei: "Pukei-Pukei",
  Radobaan: "Radobaan",
  Rathalos: "Rathalos",
  AzurRathalos: "Azur Rathalos",
  Rathian: "Rathian",
  PinkRathian: "Pink Rathian",
  Teostra: "Teostra",
  TobiKadashi: "Tobi-Kadashi",
  TzitziYaKu: "Tzitzi-Ya-Ku",
  Uragaan: "Uragaan",
  VaalHazak: "Vaal Hazak",
  Leshen: "Leshen",
  XenoJiva: "Xeno'Jiva",
  ZorahMagdaros: "Zorah Magdaros",
  Banbaro: "Banbaro",
  Beotodus: "Beotodus",
  TobiKadashiViper: "Viper Tobi-Kadashi",
  PaolumuBelladone: "Nightshade Paolumu",
  Barioth: "Barioth",
  Nargacuga: "Nargacuga",
  Glavenus: "Glavenus",
  Tigrex: "Tigrex",
  Brachydios: "Brachydios",
  ShriekingLegiana: "Shrieking Legiana",
  FulgurAnjanath: "Fulgur Anjanath",
  AcidicGlavenus: "Acidic Glavenus",
  EbonyOdogaron: "Ebony Odogaron",
  Velkhana: "Velkhana",
  SeethingBazelgeuse: "Seething Bazelgeuse",
  BlackveilVaalHazak: "Blackveil Vaal Hazak",
  Namielle: "Namielle",
  SavageDeviljho: "Savage Deviljho",
  RuinerNergigante: "Ruiner Nergigante",
  SharaIshvalda: "Shara Ishvalda",
  Zinogre: "Zinogre",
  YianGaruga: "Yian Garuga",
  ScarredYianGaruga: "Scarred Yian Garuga",
  GoldRathian: "Gold Rathian",
  SilverRathalos: "Silver Rathalos",
  BruteTigrex: "Brute Tigrex",
  CoralPukeiPukei: "Coral Pukei-Pukei",
  StygianZinogre: "Stygian Zinogre",
  Rajang: "Rajang",
  FuriousRajang: "Furious Rajang",
  FrostfangBarioth: "Frostfang Barioth",
  RagingBrachydios: "Raging Brachydios",
  SafiJiva: "Safi'Jiva",
  Alatreon: "Alatreon",
  Fatalis: "Fatalis",
  GreenNargacuga: "Green Nargacuga",
  HellbladeGlavenus: "Hellblade Glavenus",
  CrimsonFatalis: "Crimson Fatalis",
  WhiteFatalis: "White Fatalis",
  Abiogladius: "Abiogladius",
}

export function getFrenchMHWIMonsterNames(monster_name: MHWIMonsterSpecies) {
  return frenchMonsterlist[monster_name]
}

export function getEnglishMHWIMonsterNames(monster_name: MHWIMonsterSpecies) {
  return englishMonsterlist[monster_name]
}
